/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminErpRouteImport } from './routes/admin/erp'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminErpIndexRouteImport } from './routes/admin/erp/index'
import { Route as AdminErpWhatsappRouteImport } from './routes/admin/erp/whatsapp'
import { Route as AdminErpTransactionsRouteImport } from './routes/admin/erp/transactions'
import { Route as AdminErpSuppliersRouteImport } from './routes/admin/erp/suppliers'
import { Route as AdminErpReceiptsRouteImport } from './routes/admin/erp/receipts'
import { Route as AdminErpNotificationsRouteImport } from './routes/admin/erp/notifications'
import { Route as AdminErpMaterialsRouteImport } from './routes/admin/erp/materials'
import { Route as AdminErpInvoicesRouteImport } from './routes/admin/erp/invoices'
import { Route as AdminErpCustomersRouteImport } from './routes/admin/erp/customers'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/users.lazy').then((d) => d.Route))
const AdminErpRoute = AdminErpRouteImport.update({
  id: '/admin/erp',
  path: '/admin/erp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/erp.lazy').then((d) => d.Route))
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/categories.lazy').then((d) => d.Route),
)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/bookings.lazy').then((d) => d.Route),
)
const AdminErpIndexRoute = AdminErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/index.lazy').then((d) => d.Route),
)
const AdminErpWhatsappRoute = AdminErpWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/whatsapp.lazy').then((d) => d.Route),
)
const AdminErpTransactionsRoute = AdminErpTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/transactions.lazy').then((d) => d.Route),
)
const AdminErpSuppliersRoute = AdminErpSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/suppliers.lazy').then((d) => d.Route),
)
const AdminErpReceiptsRoute = AdminErpReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/receipts.lazy').then((d) => d.Route),
)
const AdminErpNotificationsRoute = AdminErpNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/notifications.lazy').then((d) => d.Route),
)
const AdminErpMaterialsRoute = AdminErpMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/materials.lazy').then((d) => d.Route),
)
const AdminErpInvoicesRoute = AdminErpInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/invoices.lazy').then((d) => d.Route),
)
const AdminErpCustomersRoute = AdminErpCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminErpRoute,
} as any).lazy(() =>
  import('./routes/admin/erp/customers.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/erp': typeof AdminErpRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/erp/customers': typeof AdminErpCustomersRoute
  '/admin/erp/invoices': typeof AdminErpInvoicesRoute
  '/admin/erp/materials': typeof AdminErpMaterialsRoute
  '/admin/erp/notifications': typeof AdminErpNotificationsRoute
  '/admin/erp/receipts': typeof AdminErpReceiptsRoute
  '/admin/erp/suppliers': typeof AdminErpSuppliersRoute
  '/admin/erp/transactions': typeof AdminErpTransactionsRoute
  '/admin/erp/whatsapp': typeof AdminErpWhatsappRoute
  '/admin/erp/': typeof AdminErpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/erp/customers': typeof AdminErpCustomersRoute
  '/admin/erp/invoices': typeof AdminErpInvoicesRoute
  '/admin/erp/materials': typeof AdminErpMaterialsRoute
  '/admin/erp/notifications': typeof AdminErpNotificationsRoute
  '/admin/erp/receipts': typeof AdminErpReceiptsRoute
  '/admin/erp/suppliers': typeof AdminErpSuppliersRoute
  '/admin/erp/transactions': typeof AdminErpTransactionsRoute
  '/admin/erp/whatsapp': typeof AdminErpWhatsappRoute
  '/admin/erp': typeof AdminErpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/erp': typeof AdminErpRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/erp/customers': typeof AdminErpCustomersRoute
  '/admin/erp/invoices': typeof AdminErpInvoicesRoute
  '/admin/erp/materials': typeof AdminErpMaterialsRoute
  '/admin/erp/notifications': typeof AdminErpNotificationsRoute
  '/admin/erp/receipts': typeof AdminErpReceiptsRoute
  '/admin/erp/suppliers': typeof AdminErpSuppliersRoute
  '/admin/erp/transactions': typeof AdminErpTransactionsRoute
  '/admin/erp/whatsapp': typeof AdminErpWhatsappRoute
  '/admin/erp/': typeof AdminErpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/impact'
    | '/login'
    | '/my-bookings'
    | '/partner'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/terms'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/erp'
    | '/admin/users'
    | '/admin/'
    | '/admin/erp/customers'
    | '/admin/erp/invoices'
    | '/admin/erp/materials'
    | '/admin/erp/notifications'
    | '/admin/erp/receipts'
    | '/admin/erp/suppliers'
    | '/admin/erp/transactions'
    | '/admin/erp/whatsapp'
    | '/admin/erp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/impact'
    | '/login'
    | '/my-bookings'
    | '/partner'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/terms'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/users'
    | '/admin'
    | '/admin/erp/customers'
    | '/admin/erp/invoices'
    | '/admin/erp/materials'
    | '/admin/erp/notifications'
    | '/admin/erp/receipts'
    | '/admin/erp/suppliers'
    | '/admin/erp/transactions'
    | '/admin/erp/whatsapp'
    | '/admin/erp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/impact'
    | '/login'
    | '/my-bookings'
    | '/partner'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/terms'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/erp'
    | '/admin/users'
    | '/admin/'
    | '/admin/erp/customers'
    | '/admin/erp/invoices'
    | '/admin/erp/materials'
    | '/admin/erp/notifications'
    | '/admin/erp/receipts'
    | '/admin/erp/suppliers'
    | '/admin/erp/transactions'
    | '/admin/erp/whatsapp'
    | '/admin/erp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminErpRoute: typeof AdminErpRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/erp': {
      id: '/admin/erp'
      path: '/admin/erp'
      fullPath: '/admin/erp'
      preLoaderRoute: typeof AdminErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/erp/': {
      id: '/admin/erp/'
      path: '/'
      fullPath: '/admin/erp/'
      preLoaderRoute: typeof AdminErpIndexRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/whatsapp': {
      id: '/admin/erp/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/erp/whatsapp'
      preLoaderRoute: typeof AdminErpWhatsappRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/transactions': {
      id: '/admin/erp/transactions'
      path: '/transactions'
      fullPath: '/admin/erp/transactions'
      preLoaderRoute: typeof AdminErpTransactionsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/suppliers': {
      id: '/admin/erp/suppliers'
      path: '/suppliers'
      fullPath: '/admin/erp/suppliers'
      preLoaderRoute: typeof AdminErpSuppliersRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/receipts': {
      id: '/admin/erp/receipts'
      path: '/receipts'
      fullPath: '/admin/erp/receipts'
      preLoaderRoute: typeof AdminErpReceiptsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/notifications': {
      id: '/admin/erp/notifications'
      path: '/notifications'
      fullPath: '/admin/erp/notifications'
      preLoaderRoute: typeof AdminErpNotificationsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/materials': {
      id: '/admin/erp/materials'
      path: '/materials'
      fullPath: '/admin/erp/materials'
      preLoaderRoute: typeof AdminErpMaterialsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/invoices': {
      id: '/admin/erp/invoices'
      path: '/invoices'
      fullPath: '/admin/erp/invoices'
      preLoaderRoute: typeof AdminErpInvoicesRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/customers': {
      id: '/admin/erp/customers'
      path: '/customers'
      fullPath: '/admin/erp/customers'
      preLoaderRoute: typeof AdminErpCustomersRouteImport
      parentRoute: typeof AdminErpRoute
    }
  }
}

interface AdminErpRouteChildren {
  AdminErpCustomersRoute: typeof AdminErpCustomersRoute
  AdminErpInvoicesRoute: typeof AdminErpInvoicesRoute
  AdminErpMaterialsRoute: typeof AdminErpMaterialsRoute
  AdminErpNotificationsRoute: typeof AdminErpNotificationsRoute
  AdminErpReceiptsRoute: typeof AdminErpReceiptsRoute
  AdminErpSuppliersRoute: typeof AdminErpSuppliersRoute
  AdminErpTransactionsRoute: typeof AdminErpTransactionsRoute
  AdminErpWhatsappRoute: typeof AdminErpWhatsappRoute
  AdminErpIndexRoute: typeof AdminErpIndexRoute
}

const AdminErpRouteChildren: AdminErpRouteChildren = {
  AdminErpCustomersRoute: AdminErpCustomersRoute,
  AdminErpInvoicesRoute: AdminErpInvoicesRoute,
  AdminErpMaterialsRoute: AdminErpMaterialsRoute,
  AdminErpNotificationsRoute: AdminErpNotificationsRoute,
  AdminErpReceiptsRoute: AdminErpReceiptsRoute,
  AdminErpSuppliersRoute: AdminErpSuppliersRoute,
  AdminErpTransactionsRoute: AdminErpTransactionsRoute,
  AdminErpWhatsappRoute: AdminErpWhatsappRoute,
  AdminErpIndexRoute: AdminErpIndexRoute,
}

const AdminErpRouteWithChildren = AdminErpRoute._addFileChildren(
  AdminErpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminErpRoute: AdminErpRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
