/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminErpRouteImport } from './routes/admin/erp'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminErpIndexRouteImport } from './routes/admin/erp/index'
import { Route as AdminErpWhatsappRouteImport } from './routes/admin/erp/whatsapp'
import { Route as AdminErpTransactionsRouteImport } from './routes/admin/erp/transactions'
import { Route as AdminErpSuppliersRouteImport } from './routes/admin/erp/suppliers'
import { Route as AdminErpReceiptsRouteImport } from './routes/admin/erp/receipts'
import { Route as AdminErpMaterialsRouteImport } from './routes/admin/erp/materials'
import { Route as AdminErpInvoicesRouteImport } from './routes/admin/erp/invoices'
import { Route as AdminErpCustomersRouteImport } from './routes/admin/erp/customers'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErpRoute = AdminErpRouteImport.update({
  id: '/admin/erp',
  path: '/admin/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErpIndexRoute = AdminErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpWhatsappRoute = AdminErpWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpTransactionsRoute = AdminErpTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpSuppliersRoute = AdminErpSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpReceiptsRoute = AdminErpReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpMaterialsRoute = AdminErpMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpInvoicesRoute = AdminErpInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminErpRoute,
} as any)
const AdminErpCustomersRoute = AdminErpCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminErpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/erp': typeof AdminErpRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/erp/customers': typeof AdminErpCustomersRoute
  '/admin/erp/invoices': typeof AdminErpInvoicesRoute
  '/admin/erp/materials': typeof AdminErpMaterialsRoute
  '/admin/erp/receipts': typeof AdminErpReceiptsRoute
  '/admin/erp/suppliers': typeof AdminErpSuppliersRoute
  '/admin/erp/transactions': typeof AdminErpTransactionsRoute
  '/admin/erp/whatsapp': typeof AdminErpWhatsappRoute
  '/admin/erp/': typeof AdminErpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/erp/customers': typeof AdminErpCustomersRoute
  '/admin/erp/invoices': typeof AdminErpInvoicesRoute
  '/admin/erp/materials': typeof AdminErpMaterialsRoute
  '/admin/erp/receipts': typeof AdminErpReceiptsRoute
  '/admin/erp/suppliers': typeof AdminErpSuppliersRoute
  '/admin/erp/transactions': typeof AdminErpTransactionsRoute
  '/admin/erp/whatsapp': typeof AdminErpWhatsappRoute
  '/admin/erp': typeof AdminErpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/erp': typeof AdminErpRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/erp/customers': typeof AdminErpCustomersRoute
  '/admin/erp/invoices': typeof AdminErpInvoicesRoute
  '/admin/erp/materials': typeof AdminErpMaterialsRoute
  '/admin/erp/receipts': typeof AdminErpReceiptsRoute
  '/admin/erp/suppliers': typeof AdminErpSuppliersRoute
  '/admin/erp/transactions': typeof AdminErpTransactionsRoute
  '/admin/erp/whatsapp': typeof AdminErpWhatsappRoute
  '/admin/erp/': typeof AdminErpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-bookings'
    | '/rates'
    | '/register'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/erp'
    | '/admin/users'
    | '/admin/'
    | '/admin/erp/customers'
    | '/admin/erp/invoices'
    | '/admin/erp/materials'
    | '/admin/erp/receipts'
    | '/admin/erp/suppliers'
    | '/admin/erp/transactions'
    | '/admin/erp/whatsapp'
    | '/admin/erp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-bookings'
    | '/rates'
    | '/register'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/users'
    | '/admin'
    | '/admin/erp/customers'
    | '/admin/erp/invoices'
    | '/admin/erp/materials'
    | '/admin/erp/receipts'
    | '/admin/erp/suppliers'
    | '/admin/erp/transactions'
    | '/admin/erp/whatsapp'
    | '/admin/erp'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-bookings'
    | '/rates'
    | '/register'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/erp'
    | '/admin/users'
    | '/admin/'
    | '/admin/erp/customers'
    | '/admin/erp/invoices'
    | '/admin/erp/materials'
    | '/admin/erp/receipts'
    | '/admin/erp/suppliers'
    | '/admin/erp/transactions'
    | '/admin/erp/whatsapp'
    | '/admin/erp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  RatesRoute: typeof RatesRoute
  RegisterRoute: typeof RegisterRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminErpRoute: typeof AdminErpRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/erp': {
      id: '/admin/erp'
      path: '/admin/erp'
      fullPath: '/admin/erp'
      preLoaderRoute: typeof AdminErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/erp/': {
      id: '/admin/erp/'
      path: '/'
      fullPath: '/admin/erp/'
      preLoaderRoute: typeof AdminErpIndexRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/whatsapp': {
      id: '/admin/erp/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/erp/whatsapp'
      preLoaderRoute: typeof AdminErpWhatsappRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/transactions': {
      id: '/admin/erp/transactions'
      path: '/transactions'
      fullPath: '/admin/erp/transactions'
      preLoaderRoute: typeof AdminErpTransactionsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/suppliers': {
      id: '/admin/erp/suppliers'
      path: '/suppliers'
      fullPath: '/admin/erp/suppliers'
      preLoaderRoute: typeof AdminErpSuppliersRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/receipts': {
      id: '/admin/erp/receipts'
      path: '/receipts'
      fullPath: '/admin/erp/receipts'
      preLoaderRoute: typeof AdminErpReceiptsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/materials': {
      id: '/admin/erp/materials'
      path: '/materials'
      fullPath: '/admin/erp/materials'
      preLoaderRoute: typeof AdminErpMaterialsRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/invoices': {
      id: '/admin/erp/invoices'
      path: '/invoices'
      fullPath: '/admin/erp/invoices'
      preLoaderRoute: typeof AdminErpInvoicesRouteImport
      parentRoute: typeof AdminErpRoute
    }
    '/admin/erp/customers': {
      id: '/admin/erp/customers'
      path: '/customers'
      fullPath: '/admin/erp/customers'
      preLoaderRoute: typeof AdminErpCustomersRouteImport
      parentRoute: typeof AdminErpRoute
    }
  }
}

interface AdminErpRouteChildren {
  AdminErpCustomersRoute: typeof AdminErpCustomersRoute
  AdminErpInvoicesRoute: typeof AdminErpInvoicesRoute
  AdminErpMaterialsRoute: typeof AdminErpMaterialsRoute
  AdminErpReceiptsRoute: typeof AdminErpReceiptsRoute
  AdminErpSuppliersRoute: typeof AdminErpSuppliersRoute
  AdminErpTransactionsRoute: typeof AdminErpTransactionsRoute
  AdminErpWhatsappRoute: typeof AdminErpWhatsappRoute
  AdminErpIndexRoute: typeof AdminErpIndexRoute
}

const AdminErpRouteChildren: AdminErpRouteChildren = {
  AdminErpCustomersRoute: AdminErpCustomersRoute,
  AdminErpInvoicesRoute: AdminErpInvoicesRoute,
  AdminErpMaterialsRoute: AdminErpMaterialsRoute,
  AdminErpReceiptsRoute: AdminErpReceiptsRoute,
  AdminErpSuppliersRoute: AdminErpSuppliersRoute,
  AdminErpTransactionsRoute: AdminErpTransactionsRoute,
  AdminErpWhatsappRoute: AdminErpWhatsappRoute,
  AdminErpIndexRoute: AdminErpIndexRoute,
}

const AdminErpRouteWithChildren = AdminErpRoute._addFileChildren(
  AdminErpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  RatesRoute: RatesRoute,
  RegisterRoute: RegisterRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminErpRoute: AdminErpRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
